name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  haskell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.2'
          cabal-version: '3.6'
      - run: |
          cd haskell
          cabal update
          cabal build

  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo test --verbose --manifest-path rust/Cargo.toml

  zig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.11.0
      - run: zig version

  racket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Bogdanp/setup-racket@v1
        with:
          version: '8.17'
      - run: |
          cd racket
          racket main.rkt
