name: Zig CI

on:
  push:
    paths:
      - 'zig/**'
  pull_request:
    paths:
      - 'zig/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: zig
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.11.0
      - name: Test
        run: zig build test
